name:           programming-in-haskell
version:        0.1.0.0
author:         Dinko Osrecki
github:         osrecki/programming-in-haskell
description:    <https://github.com/osrecki/programming-in-haskell#readme>

dependencies:
- base >=4.7 && <5
- containers ==0.5.11.0
- deepseq ==1.4.3.0
- directory ==1.3.2.1
- filepath ==1.4.2
- optparse-applicative ==0.14.2.0

library:
  source-dirs: .
